### ISSUE TITLE
Using with selects

### ISSUE THREAD

**Issue by ErikParso** [vdjurdjevic/material-scrollbars#1]
Hello, can you please provide an example how to integrate overlay scrollbars with MuiSelect in popover paper ? In best case how do i configure it in template ?

**Comment by vdjurdjevic** [comment]
@ErikParso Hi Erik, sorry for the delay.. Did you manage to integrate it? I think you can do something similar to autocomplete integration.

**Comment by ErikParso** [comment]
Yes i managed to configure it within template. I overrided props.MenuProps.PaperProps.Component. Component i used:

```
export const SelectMenuDialog = React.forwardRef<typeof Paper, PaperProps>(({ children, className, ...props }, ref) =>
    <Paper {...props} ref={ref} className={classes(className, 'select-menu-dialog')}>
        <Scrollbars> // used OverlayScrollbars library
            {children}
        </Scrollbars>
    </Paper>);
```
